language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: dhven4RtpFhW65FEmS3/XxFtaTc+3vkmJz6bFkT/4lGDF13qTY71A44OMpKOzjmqjj9nfX9cd7vDj3mvxyx7eIl9lcZWg225kFCYOzQ4dA3JQaskmWIqHQEhdYTx4EVPTN4j5wS+GA8dZyb6Mfkv/nHz3vlDKi4XNGHsCwm3XnLt37iE6vJ4hNlhpRBAcn5MYBNFQSJXW5um8TDhOPZn/riSwXDqXx9XOPaXDcGMDB3C2eVpQ6RdyEs1MgJxYdiMHUKvRnsIzD9IFTrzZLuwCPWkE/sKi28n757kHMXNINXHZKlBm7sGT4m7PGIP7LUcH9tZYsEOTuoAPZIyjQSAPxvV6pzPJgztRsJH5Q7+L372EHzDYpx/v0XpLOAEVE+dZ9OWF91AuNYWp7lKCqZ7M7Skhnxmes6A9ttOFWkBOzJ7bnmAzSQXvcbgWeMSzeirqejoCPCrqzaI0Y79WeqLxomA4INtQ9C5A448ZxkllPQ17bzjp9KZ398VF+FObdWQ78mpE4e1r+AJ/MSUigf9lIjJY60/nIzjq0a6+EZhHychBlPNhDX4gqASQExzI8//1k4kXyVs7KWUgQgoK7HSK+e1BOjckG/AxU6X3S0vtiVHN+k92rwmsmZS3jfvDnzvYdHDMF6ui3IdrKTFkApMO1PlSKBctsMYfE55yqPcM+I=
  app: pure-gorge-4399
  on:
    repo: cblignaut/flasktaskr
